--- 
- ensemble-drupal: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-drupal
    github_url: https://github.com/mmm/ensemble-drupal
- ensemble-rails: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-rails
    github_url: https://github.com/mmm/ensemble-rails
- ensemble-hadoop: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-hadoop
    github_url: https://github.com/mmm/ensemble-hadoop
- ensemble-template: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-template
    github_url: https://github.com/mmm/ensemble-template
- testrails: 
    launchpad_url: lp:~mark-mims/+junk/testrails
    github_url: https://github.com/mmm/testrails
- testnode: 
    launchpad_url: lp:~mark-mims/+junk/testnode
    github_url: https://github.com/mmm/testnode
- ensemble-node.js: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-node.js
    github_url: https://github.com/mmm/ensemble-node.js
- ensemble-postgresql: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-postgresql
    github_url: https://github.com/mmm/ensemble-postgresql
- ensemble-varnish: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-varnish
    github_url: https://github.com/mmm/ensemble-varnish
- ensemble-lxc-container: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-lxc-container
    github_url: https://github.com/mmm/ensemble-lxc-container
- ensemble-nfs-client: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-nfs-client
    github_url: https://github.com/mmm/ensemble-nfs-client
- ensemble-hummingbird: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-hummingbird
    github_url: https://github.com/mmm/ensemble-hummingbird
- ensemble-etherpad-lite: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-etherpad-lite
    github_url: https://github.com/mmm/ensemble-etherpad-lite
- ensemble-mynodeapp: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-mynodeapp
    github_url: https://github.com/mmm/ensemble-mynodeapp
- ensemble-mongodb: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-mongodb
    github_url: https://github.com/mmm/ensemble-mongodb
- ensemble-mysql: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-mysql
    github_url: https://github.com/mmm/ensemble-mysql
- ensemble-formula-tests: 
    launchpad_url: lp:~mark-mims/+junk/ensemble-formula-tests
    github_url: https://github.com/mmm/ensemble-formula-tests
