--- 
- !ruby/object:Project 
  name: ensemble-drupal
  launchpad_url: lp:~mark-mims/+junk/ensemble-drupal
  github_url: https://github.com/mmm/ensemble-drupal
- !ruby/object:Project 
  name: ensemble-rails
  launchpad_url: lp:~mark-mims/+junk/ensemble-rails
  github_url: https://github.com/mmm/ensemble-rails
- !ruby/object:Project 
  name: ensemble-hadoop
  launchpad_url: lp:~mark-mims/+junk/ensemble-hadoop
  github_url: https://github.com/mmm/ensemble-hadoop
- !ruby/object:Project 
  name: ensemble-template
  launchpad_url: lp:~mark-mims/+junk/ensemble-template
  github_url: https://github.com/mmm/ensemble-template
- !ruby/object:Project 
  name: testrails
  launchpad_url: lp:~mark-mims/+junk/testrails
  github_url: https://github.com/mmm/testrails
- !ruby/object:Project 
  name: testnode
  launchpad_url: lp:~mark-mims/+junk/testnode
  github_url: https://github.com/mmm/testnode
- !ruby/object:Project 
  name: ensemble-node.js
  launchpad_url: lp:~mark-mims/+junk/ensemble-node.js
  github_url: https://github.com/mmm/ensemble-node.js
- !ruby/object:Project 
  name: ensemble-postgresql
  launchpad_url: lp:~mark-mims/+junk/ensemble-postgresql
  github_url: https://github.com/mmm/ensemble-postgresql
- !ruby/object:Project 
  name: ensemble-varnish
  launchpad_url: lp:~mark-mims/+junk/ensemble-varnish
  github_url: https://github.com/mmm/ensemble-varnish
- !ruby/object:Project 
  name: ensemble-lxc-container
  launchpad_url: lp:~mark-mims/+junk/ensemble-lxc-container
  github_url: https://github.com/mmm/ensemble-lxc-container
- !ruby/object:Project 
  name: ensemble-nfs-client
  launchpad_url: lp:~mark-mims/+junk/ensemble-nfs-client
  github_url: https://github.com/mmm/ensemble-nfs-client
- !ruby/object:Project 
  name: ensemble-hummingbird
  launchpad_url: lp:~mark-mims/+junk/ensemble-hummingbird
  github_url: https://github.com/mmm/ensemble-hummingbird
- !ruby/object:Project 
  name: ensemble-etherpad-lite
  launchpad_url: lp:~mark-mims/+junk/ensemble-etherpad-lite
  github_url: https://github.com/mmm/ensemble-etherpad-lite
- !ruby/object:Project 
  name: ensemble-mynodeapp
  launchpad_url: lp:~mark-mims/+junk/ensemble-mynodeapp
  github_url: https://github.com/mmm/ensemble-mynodeapp
- !ruby/object:Project 
  name: ensemble-mongodb
  launchpad_url: lp:~mark-mims/+junk/ensemble-mongodb
  github_url: https://github.com/mmm/ensemble-mongodb
- !ruby/object:Project 
  name: ensemble-mysql
  launchpad_url: lp:~mark-mims/+junk/ensemble-mysql
  github_url: https://github.com/mmm/ensemble-mysql
- !ruby/object:Project 
  name: ensemble-formula-tests
  launchpad_url: lp:~mark-mims/+junk/ensemble-formula-tests
  github_url: https://github.com/mmm/ensemble-formula-tests
